[0m21:47:38.324480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BE67A8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BE6ABC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BE6ABF80>]}


============================== 21:47:38.338613 | 1c61d6c1-a510-4569-83ef-789f7a18590d ==============================
[0m21:47:38.338613 [info ] [MainThread]: Running with dbt=1.9.3
[0m21:47:38.339615 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\hugoa\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:47:38.340631 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hugoa\DSAI_MAIN\bowen\dsai-group2\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:47:38.344194 [debug] [MainThread]: Command `dbt run` failed at 21:47:38.343156 after 0.30 seconds
[0m21:47:38.345185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BBD32990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BE67A8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000174BEB1FA70>]}
[0m21:47:38.345185 [debug] [MainThread]: Flushing usage events
[0m21:47:39.289569 [debug] [MainThread]: An error was encountered while trying to flush usage events
